/api/providers:
  get:
    summary: Returns a list of providers.
    description: Returns a list of providers by allowing query with multiple parameters as well as field selection.
    tags:
      - Providers
    produces:
      - application/json
    parameters:
      - name: max_discharges
        description: Max number of discharges
        in: query
        required: false
        schema:
          type: integer
      - name: min_discharges
        description: Min number of discharges
        in: query
        required: false
        schema:
          type: integer
      - name: max_average_covered_charges
        description: Max average covered charges
        in: query
        required: false
        schema:
          type: number
          format: float
      - name: min_average_covered_charges
        description: Min average covered charges
        in: query
        required: false
        schema:
          type: number
          format: float
      - name: max_average_medicare_payments
        description: Max average medicare payments
        in: query
        required: false
        schema:
          type: number
          format: float
      - name: min_average_medicare_payments
        description: Min average medicare payments
        in: query
        required: false
        schema:
          type: number
          format: float
      - name: state
        description: 2 Letter representing the state
        in: query
        required: false
        schema:
          type: string
      - name: fields
        description: >
          Selection of the output fields separated by `,` (comma). Possible values:
           * `Provider Name`
           * `Provider Street Address`
           * `Provider City`
           * `Provider State`
           * `Provider Zip Code`
           * `Hospital Referral Region Description`
           * `Total Discharges`
           * `Average Covered Charges`
           * `Average Total Payments`
           * `Average Medicare Payments`
        in: query
        required: false
        schema:
          type: string
    responses:
      200:
        description: A JSON array of providers
        content:
          application/json:
            schema:
              $ref: "#/definitions/providers"


definitions:
  providers:
    type: array
    items:
      type: object
      properties:
        Provider Name:
          type: string
        Provider Street Address:
          type: string
        Provider City:
          type: string
        Provider State:
          type: string
        Provider Zip Code:
          type: string
        Hospital Referral Region Description:
          type: string
        Total Discharges:
          type: integer
        Average Covered Charges:
          type: number
          format: float
        Average Total Payments:
          type: number
          format: float
        Average Medicare Payments:
          type: number
          format: float

